create table if not exists public.quizzes (
    code text primary key,
    title text not null,
    questions jsonb not null default '[]'::jsonb,
    admin_pin_hash text not null,
    access_password_hash text,
    settings jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.attempts (
    id bigint generated by default as identity primary key,
    quiz_code text not null references public.quizzes(code) on delete cascade,
    student_name text not null,
    answers jsonb not null default '{}'::jsonb,
    details jsonb not null default '[]'::jsonb,
    correct integer,
    total integer,
    score double precision,
    created_at timestamptz not null default now()
);

create index if not exists attempts_quiz_code_idx
on public.attempts (quiz_code);

alter table public.quizzes enable row level security;
alter table public.attempts enable row level security;
